databases:
  - name: books
    databaseName: books_2r33
    user: bookuser

services:
  - type: web
    name: ask-my-book
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: BOOK_DB_URL
        fromDatabase:
          name: books
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false